export const ActionTypes = {
    USER_PROFILE : "USER_PROFILE",
    USER : "USER",
    PROMOTION_VIDEO : "PROMOTION_VIDEO",
    ALL_ASKER:"ALL_ASKER",
    ACTIVE_ASKER:"ACTIVE_ASKER",
    ACHIVED_ASKER:"ACHIVED_ASKER",
    SERACH_ASKER:"SERACH_ASKER",
}